--- 
- 
  hosts: all
  tasks: 
    - 
      copy: 
        dest: "{{ item.dest }}"
        src: "{{ item.src }}"
      name: "Copy configuration files."
      with_items: 
        - 
          dest: /tmp/a.txt
          src: /tmp/dummy/a.txt
    - 
      command: "ls /tmp"
      register: dir_out
    -
      debug: var={{item}}
      with_items: dir_out.stdout_lines
    - 
      find: paths="/tmp/" recurse=yes patterns="*.txt"
      register: files_to_copy
    -
      debug: var={{item}}
      with_items: files_to_copy.files
      # first ensure our target directory exists
    - file: dest=/tmp/dummy state=directory

    # copy each file over that matches the given pattern
    - copy: src={{ item }} dest=/tmp/dummy/ owner=root mode=600
      with_fileglob:
        - /localtemp/files/*
    

