--- 
- 
  hosts: all
  tasks: 
    - 
      copy: 
        dest: "{{ item.dest }}"
        src: "{{ item.src }}"
      name: "Copy configuration files."
      with_items: 
        - 
          dest: /tmp/a.txt
          src: /tmp/dummy/a.txt
    - 
      command: "ls /tmp"
      register: dir_out
    -
      debug: var={{item}}
      with_items: dir_out.stdout_lines
    - 
      find: paths="/tmp/" recurse=yes patterns="*.txt"
      register: files_to_copy
    -
      debug: var={{item}}
      with_items: files_to_copy.files
    

